name: light_western_food
description: "갓생을 살면 경양식을 키울 수 있어요"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_screen.png
    - assets/images/login_screen_ver2.png
    - assets/images/google_login_button.png
    - assets/images/home_room.png
    - assets/images/baby_lwf.gif

dependency_overrides:
  google_sign_in_ios: 5.8.0
