// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVaE3lmAlOj-ikOOkLOxmBErNBkBnpSLU',
    appId: '1:129201603121:web:083fda24481e8ae7198b10',
    messagingSenderId: '129201603121',
    projectId: 'lightwesternfood',
    authDomain: 'lightwesternfood.firebaseapp.com',
    storageBucket: 'lightwesternfood.firebasestorage.app',
    measurementId: 'G-6KP04TT5ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfaT4D_RkAzwfzep9pQsPYfq9SH5eQDU',
    appId: '1:129201603121:android:7c3bc05f1dba4756198b10',
    messagingSenderId: '129201603121',
    projectId: 'lightwesternfood',
    storageBucket: 'lightwesternfood.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN079vLFCkEDT7-gxkqfupFc5g9JhOiSk',
    appId: '1:129201603121:ios:a57e51b810085582198b10',
    messagingSenderId: '129201603121',
    projectId: 'lightwesternfood',
    storageBucket: 'lightwesternfood.firebasestorage.app',
    iosBundleId: 'com.lightwesternfood.lightWesternFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN079vLFCkEDT7-gxkqfupFc5g9JhOiSk',
    appId: '1:129201603121:ios:a57e51b810085582198b10',
    messagingSenderId: '129201603121',
    projectId: 'lightwesternfood',
    storageBucket: 'lightwesternfood.firebasestorage.app',
    iosBundleId: 'com.lightwesternfood.lightWesternFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVaE3lmAlOj-ikOOkLOxmBErNBkBnpSLU',
    appId: '1:129201603121:web:ac41dce913b4621d198b10',
    messagingSenderId: '129201603121',
    projectId: 'lightwesternfood',
    authDomain: 'lightwesternfood.firebaseapp.com',
    storageBucket: 'lightwesternfood.firebasestorage.app',
    measurementId: 'G-E4Y0K76N0Z',
  );
}
